### PR TITLE
fix: change the encoding into utf-8

### PR DESCRIPTION
**Pull request by MistyField**

### CODE REVIEW

**Comment by MistyField** [comment]
Update: in the line 250 of parser.py `refs` is a string so when it was sliced, only 9 references could be added, and even worse, in the wrong order. So it may be changed into `references[refs] = line` and it was tested fine.

**Comment by Robaina** [comment]
Thanks so much for the PR! 

I'm planning to update BRENDApyrser to accommodate the newly available json format, see issue #9. I'll leave this PR on hold for now since most likely this issue with the references will be solved.

**Comment by MistyField** [comment]
> Thanks so much for the PR!
> 
> I'm planning to update BRENDApyrser to accommodate the newly available json format, see issue #9. I'll leave this PR on hold for now since most likely this issue with the references will be solved.

Thank you for your reply! And I successfully made a database of enzyme kinetics using [BRENDApyrser](http://54.169.242.254:5000/search), which is very powerful! For me, parsing the json is a good idea, it will save a lot of time in parsing the data, but the change in this [PR](https://github.com/Robaina/BRENDApyrser/pull/8/commits/5b1aa28145d3920c0cdcd3a806541dc0cbd71c0f) is needed regardless of whether the data format is .txt or .json since it will impact the consistency of the content in the references.

**Comment by Robaina** [comment]
Glad to hear that! It's awesome to learn that you have found the package useful!

**Comment by Robaina** [comment]
Hi @MistyField ,

sorry, could you update your branch with the current master branch to resolve these conflicts prior to merge?

**Comment by MistyField** [comment]
> Hi @MistyField ,
> 
> sorry, could you update your branch with the current master branch to resolve these conflicts prior to merge?

**Comment by MistyField** [comment]
> Hi @MistyField ,
> 
> sorry, could you update your branch with the current master branch to resolve these conflicts prior to merge?

Hello, I've updated my forked branch with the master branch:)

**Review by Robaina — CHANGES_REQUESTED** [review]
I don't want to merge this commit with the ".idea" directory from JetBrains? This is a local directory, shouldn't be in the repo. Please, could you remove it? We don't need to include ".idea" in  .gitignore either.

Otherwise, I'm fine with the rest of the PR!

**Comment by MistyField** [comment]
> I don't want to merge this commit with the ".idea" directory from JetBrains? This is a local directory, shouldn't be in the repo. Please, could you remove it? We don't need to include ".idea" in .gitignore either.
> 
> Otherwise, I'm fine with the rest of the PR!

Of course! Apologize for the inconvenience I caused by changing the .gitignore🙏

**Review by Robaina — APPROVED** [review]
Excellent! Thank you!

**Comment by Robaina** [comment]
> > I don't want to merge this commit with the ".idea" directory from JetBrains? This is a local directory, shouldn't be in the repo. Please, could you remove it? We don't need to include ".idea" in .gitignore either.
> > Otherwise, I'm fine with the rest of the PR!
> 
> Of course! Apologize for the inconvenience I caused by changing the .gitignore🙏

No worries !

**Pull request merged**
